### ISSUE TITLE
dsio query throwing error -> Missing or insufficient permissions.

### ISSUE THREAD

**Issue by Bluesir9** [nshmura/dsio#28]
I have set up the project and added the necessary environment variables to use the "dsio query" operation.  But when I use it for a Select query, it always throws the following error

rpc error: code = PermissionDenied desc = Missing or insufficient permissions.

This is happening despite the fact that I have full access to the project that I am trying to run the query against. Am I missing something?

**Comment by nshmura** [comment]
Hi,

Dose your service-account has `Cloud Datastore View` role or higher role?

**Comment by Bluesir9** [comment]
I am looking at the permissions I have for the project in the "IAM" section of the cloud console, and based on that i have read and edit access to all resources.

**Comment by nshmura** [comment]
I guess that dsio dose not detect a key-file or project-id.
Did you try to specify key-file and project-id as command line option?

like below:
```
dsio upsert --key-file ./example-foobar.json --project-id example-1234  "SELECT * FROM Book"
```
