### ISSUE TITLE
Automatic completion for blank integer

### ISSUE THREAD

**Issue by timakin** [nshmura/dsio#30]
When I directly import the same data that not changed from when they parsed with `SELECT` query, it alerts:
`[ERROR] can not parse 'strconv.ParseInt: parsing "": invalid syntax' as int.`

But I expected the integer-typed blank values would be automatically converted to `0`.

**Comment by nshmura** [comment]
@timakin Thank you for your report!
Fixed to automatically convert integer-typed blank value to 0.
https://github.com/nshmura/dsio/pull/31

**Comment by timakin** [comment]
Thanks a lot!
