### ISSUE TITLE
Data-type must not be blank

### ISSUE THREAD

**Issue by timakin** [nshmura/dsio#32]
![2018-01-14 14 22 37](https://user-images.githubusercontent.com/2871985/34913074-85e890d8-f936-11e7-8354-d85e06eef7ee.png)

By mistake I uploaded this csv, and as it shows the type of `placement`  is blank.
But the result says it "succeeded".

**Comment by nshmura** [comment]
@timakin Thanks! I fixed it to rise error if data type is blank. https://github.com/nshmura/dsio/pull/33
